### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by dspasyuk** [maxicus/ib-tws-api#24]
I get this error while trying your module in v12.16.1. NodeJS: 

Looks like the new node requires all the ES6 files named as .mjs

import { Client } from 'ib-tws-api';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

**Comment by maxicus** [comment]
let me google it for you:
https://stackoverflow.com/questions/58384179/syntaxerror-cannot-use-import-statement-outside-a-module
